name: Documentation Update 📝
description: Edit documentation in some way or form.
labels: ['documentation', 'needs triage']
title: '[Docs?]: '
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        Thanks for contributing by creating an issue! ❤️
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll docs out in and with versioning.
      options:
        - label: I have checked the latest version
          required: true
  - type: textarea
    attributes:
      label: Summary 💡
      description: Describe how what you would like to see updated.
  - type: textarea
    attributes:
      label: Motivation 🔦
      description: What are you trying to accomplish? How has the lack of this feature affected you? Providing context helps us come up with a solution that is more useful in the real world.
