name: 💅 Lint Checks

on: [merge_group, pull_request]

jobs:
  lint-js:
    runs-on: ubuntu-latest
    name: JS valid
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run lint:js

  # TODO: fix lint:ts - solid still has bad internal types

  # lint-ts:
  #   runs-on: ubuntu-latest
  #   name: TS valid
  #   steps:
  #     - uses: actions/checkout@v3.5.3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: 'pnpm'
  #     - run: npm install
  #     - run: npm run lint:ts
