name: 💅 Lint Checks

on: [merge_group, pull_request]

jobs:
  # lint-css:
  #   runs-on: ubuntu-latest
  #   name: CSS valid
  #   steps:
  #     - uses: actions/checkout@v3.5.3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: 'npm'
  #     - run: npm install
  #     - run: npm run lint:css

  lint-js:
    runs-on: ubuntu-latest
    name: JS valid
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run lint:js

  # TODO: fix lint:ts - solid still has bad internal types

  # lint-ts:
  #   runs-on: ubuntu-latest
  #   name: TS valid
  #   steps:
  #     - uses: actions/checkout@v3.5.3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #         cache: 'npm'
  #     - run: npm install
  #     - run: npm run lint:ts
